---
host: <your ip address>
user: admin
password: <your password>

# Usage:
# -------------------------------------------------------
## Specify switches. You can have any number of switches.
# switches:
# - 101
# - 102
# switch_profile: <switch_profile_name>
# interface_type: [individual | pc | vpc]
# interface_selector: <interface_selector>
# interface_policy_group: <interface_policy_group>
## Specify interface ports. You can have any number of interface ports.
# interface_ports:
# - 1/33
# - 1/34

switches:
- 101
- 102
switch_profile: switch_profile10
interface_type: individual
interface_selector: interface_selector10
interface_policy_group: interface_policy_group1
interface_ports:
- 1/33
- 1/34
